apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: clo835-binding
  namespace: default
subjects:
  - kind: ServiceAccount
    name: clo835-group5
    namespace: default
    apiGroup: ""
roleRef:
  kind: Role
  name: CLO835-final-group5
  apiGroup: rbac.authorization.k8s.io