apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: CLO835-final-group5
  namespace: default
rules:
  - apiGroups: [""]
    resources: ["namespaces"]
    verbs: ["create", "get", "list"]