apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-group5-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql-group5-deployment
        image: 992332505002.dkr.ecr.us-east-1.amazonaws.com/pt-final:latest
        ports:
        - containerPort: 3306
        env:
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
                secretKeyRef:
                  name: group5-mysql-secret
                  key: password
        